company_name: "capitaland"  # Options: capitaland, dbs, grab, sq

# file Paths
data_folder: "data"
markdown_folder: "markdown_files"
outputs_folder: "outputs"
logs_folder: "logs"
question_set_path: "question_set.md"

pdf_files:
  capitaland: "Capitaland 2024.pdf"
  dbs: "dbs-annual-report-2024.pdf"
  grab: "Grab 2024.pdf"
  sq: "SQ 2024.pdf"

embedding_model: "all-MiniLM-L6-v2"

llm_provider: "openai"
claude_model: "claude-3-haiku-20240307"
openai_model: "gpt-4o-mini"
ollama_model: "qwen3:14b"
ollama_url: "http://localhost:11434"

docling:
  export_format: "markdown"

chunking:
  min_chunk_size: 100
  max_chunk_size: 2000

semantic_chunking:
  similarity_threshold: 0.70 
  max_merged_size: 3000 
